nesqlExporterVersion=1.04

minecraftVersion=1.7.10
forgeVersion=10.13.4.1614

autoValueVersion=1.10.4
protoBufferVersion=4.33.4
lombokVersion=1.18.32
msgpackVersion=0.9.8

# Be careful if you want to update these versions. Later versions may require newer Java than 1.8
springDataVersion=2.7.7
# 3.1.0 requires newer Java than 1.8
jakartaPersistenceVersion=3.0.0
# Newer Hibernate requires newer Java than 1.8, or doesn't support Jakarta
hibernateVersion=5.6.15.Final
hsqldbVersion=2.7.2
postgresqlVersion=42.7.3

neiVersion=2.5.27-GTNH

mobsInfoVersion=0.2.6-GTNH

avaritiaVersion=1.49

gregTech5Version=5.09.45.161
industrialCraft2Version=2.2.828
forestryVersion=4.11.4
railcraftVersion=9.15.15
buildCraftVersion=7.1.48
enderIoVersion=2.10.12
projectRedVersion=4.12.8-GTNH

thaumcraftVersion=4.2.3.5
thaumcraftNeiVersion=2241913

betterQuestingVersion=3.5.10-GTNH
