package com.github.dcysteine.nesql.exporter.local;

import java.util.ArrayList;
import java.util.List;

final class RawExportCounts {
    long items;
    long fluids;
    long recipes;
    long recipeTypes;
    long renderAssets;
    long itemModFiles;
    long recipeModFiles;
    long canonicalFiles;
    long rawItems;
    long rawFluids;
    long rawRecipes;
    long rawGroups;
    long rawNeiOrderEntries;
    long neiRuntimePanelItems;
    long neiExportOnlyItems;
    long neiBrowserItems;
    long neiDefaultEntries;
    long neiFallbackGroups;
    long neiNativeGroups;
    long neiSyntheticGroups;
    long neiGuidFilterRules;
    long neiHiddenItemRules;
    long neiHiddenItems;
    long neiRepresentativeMismatches;
    long neiHandlers;
    long neiHandlerLayouts;
    long uiFamilyCensusHandlers;
    long uiFamilyCensusFamilies;
    long uiTemplateCatalogHandlers;
    long uiTemplateCatalogTemplates;
    long uiTemplateCatalogFamilies;
    long nativeUiLayouts;
    long nativeUiSlots;
    long nativeUiRects;
    long nativeUiPrimitives;
    long nativeUiMissingSurfaces;
    long nativeUiSlotBoundsViolations;
    long nativeUiRectBoundsViolations;
    long nativeUiPrimitiveBoundsViolations;
    long nativeUiBackgroundBoundsViolations;
    long nativeUiCoordinateContractViolations;
    long nativeUiInteractionContractViolations;
    List<String> nativeUiMissingSurfaceSamples = new ArrayList<String>();
    List<String> nativeUiSlotBoundsViolationSamples = new ArrayList<String>();
    List<String> nativeUiRectBoundsViolationSamples = new ArrayList<String>();
    List<String> nativeUiPrimitiveBoundsViolationSamples = new ArrayList<String>();
    List<String> nativeUiBackgroundBoundsViolationSamples = new ArrayList<String>();
    List<String> nativeUiCoordinateContractViolationSamples = new ArrayList<String>();
    List<String> nativeUiInteractionContractViolationSamples = new ArrayList<String>();
    long rawTextures;
    long rawAnimations;
    long rawEntities;
    long rawBrowserAtlasAssets;
    long renderBackendFacts;
    long renderBackendAngelica;
    long renderTextureSprites;
    long renderTextureSpritesMissingTiming;
    long renderItemRenderers;
    long renderShaderItems;
    long renderShaderItemsRequiringCapture;
    long renderShaderItemsMissingCapture;
    List<String> renderShaderItemsMissingCaptureSamples = new ArrayList<String>();
    long renderUnknownSpecialRenderers;
    long renderFramebufferCaptures;
    long renderFramebufferCapturesWithoutFrames;
    List<String> renderFramebufferCapturesWithoutFramesSamples = new ArrayList<String>();
    long semanticTotalItems;
    long semanticTaggedItems;
    long semanticClassifiedTaggedItems;
    long semanticUnclassifiedTaggedItems;
    long semanticEstimatedPublicItems;
    long semanticFamilyCount;
    long semanticItems;
    long semanticVariants;
    long semanticPayloads;
    long semanticIdentityMapRows;
}
