package com.github.dcysteine.nesql.exporter.main;

/**
 * Transitional export stages for the NESQL++ single-orchestrator migration.
 */
public enum ExportStage {
    INITIALIZE_REPOSITORY,
    INITIALIZE_DATABASE,
    INITIALIZE_PLUGINS,
    COLLECT_PLUGIN_DATA,
    WRITE_UI_FAMILY_CENSUS,
    WRITE_MOD_BASED_ITEMS,
    WRITE_MOD_BASED_RECIPES,
    WRITE_MULTIBLOCK_BLUEPRINTS,
    WRITE_BLOCK_FACE_METADATA,
    WRITE_CANONICAL_SNAPSHOT,
    COMMIT_DATABASE,
    ROLLBACK_DATABASE,
    RENDER_IMAGES,
    WRITE_RENDER_ASSET_MANIFEST,
    WRITE_ANIMATION_MANIFEST,
    WRITE_ATLAS_PACKS,
    WRITE_ANIMATED_ATLAS_PACKS,
    WRITE_ATLAS_REGISTRY,
    WRITE_RENDER_INDEX,
    WRITE_BROWSER_LAYOUT_INDEX,
    WRITE_BROWSER_ATLAS_INDEX,
    WRITE_RAW_EXPORT_SIDECAR,
    COMPLETE
}
